# frozen_string_literal: true

# add the internal gem server (for internal gems)
# bundler prefers last 'source' first
source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'cucumber', '~> 3.1'
gem 'config', '~> 2.0'
gem 'rake', '~> 12.3', require: false

gem 'rspec'

gem 'rubocop', '~> 0.71', require: false

gem 'selenium-webdriver', '~> 3.142'
gem 'webdrivers'

gem 'parallel_tests', '~> 2.29', require: false