require 'parallel_tests'

task default: ['test:local']

namespace :test do
  number_of_processes = 7

  desc 'Run the functional test suite locally'
  task :local do
    ENV['HEADLESS_BROWSER'] = 'true'
    ParallelTests::CLI.new.run(%W[-n #{number_of_processes} --type cucumber -- -f pretty -- features])
  end

  desc 'Run the functional test suite in CI'
  task ci: %i[chutney lint] do
    ParallelTests::CLI.new.run(%W[-n #{number_of_processes} --type cucumber -- -f ParallelReportPortal::Cucumber::Formatter --out /dev/null -f progress --retry 1 -- features])
  end

  desc 'Run the functional test suite in CD'
  task :cd do
    # number of processes limited to 4 to run in cd
    ParallelTests::CLI.new.run(%W[-n 4 --type cucumber -- -f ParallelReportPortal::Cucumber::Formatter --out /dev/null -f progress --retry 1 -- features])
  end
end
